import type { MenuLabels } from "@shared/app-menu";
import type { MessageKey } from "../../i18n";

type Translate = (key: MessageKey) => string;

export function buildMenuLabels(t: Translate): MenuLabels {
  return {
    file: t("menu.file"),
    edit: t("menu.edit"),
    view: t("menu.view"),
    help: t("menu.help"),
    new: t("menu.new"),
    newTab: t("menu.newTab"),
    newRunnerTab: t("menu.newRunnerTab"),
    newWindow: t("menu.newWindow"),
    import: t("menu.import"),
    importOpenapi: t("menu.importOpenapi"),
    importCurl: t("menu.importCurl"),
    settings: t("menu.settings"),
    closeWindow: t("menu.closeWindow"),
    closeTab: t("menu.closeTab"),
    forceCloseTab: t("menu.forceCloseTab"),
    exit: t("menu.exit"),
    undo: t("menu.undo"),
    redo: t("menu.redo"),
    cut: t("menu.cut"),
    copy: t("menu.copy"),
    paste: t("menu.paste"),
    pasteMatch: t("menu.pasteMatch"),
    delete: t("menu.delete"),
    selectAll: t("menu.selectAll"),
    fullScreen: t("menu.fullScreen"),
    zoomIn: t("menu.zoomIn"),
    zoomOut: t("menu.zoomOut"),
    resetZoom: t("menu.resetZoom"),
    toggleLeftSidebar: t("menu.toggleLeftSidebar"),
    toggleTwoPane: t("menu.toggleTwoPane"),
    toggleWorkbench: t("menu.toggleWorkbench"),
    toggleRightSidebar: t("menu.toggleRightSidebar"),
    swapSidebars: t("menu.swapSidebars"),
    resetLayout: t("menu.resetLayout"),
    goBack: t("menu.goBack"),
    goForward: t("menu.goForward"),
    nextTab: t("menu.nextTab"),
    prevTab: t("menu.prevTab"),
    showConsole: t("menu.showConsole"),
    developer: t("menu.developer"),
    toggleDevTools: t("menu.toggleDevTools"),
    checkUpdates: t("menu.checkUpdates"),
    clearCache: t("menu.clearCache"),
    hwAccel: t("menu.hwAccel"),
    region: t("menu.region"),
    regionUs: t("menu.regionUs"),
    regionEu: t("menu.regionEu"),
    regionAsia: t("menu.regionAsia"),
    docs: t("menu.docs"),
    github: t("menu.github"),
    twitter: t("menu.twitter"),
    support: t("menu.support"),
    about: t("menu.about"),
    restartTitle: t("menu.restartTitle"),
    restartHwAccel: t("menu.hwAccelRestart"),
  };
}
